# Generated by Django 5.2.11 on 2026-03-03 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('total', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='placed', max_length=20)),
                ('pay_method', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mrp', models.PositiveIntegerField(help_text='Maximum Retail Price (₹)')),
                ('price', models.PositiveIntegerField(help_text='Selling Price (₹)')),
                ('sizes', models.JSONField(default=list, help_text='e.g. ["S","M","L","XL"]')),
                ('description', models.TextField(blank=True)),
                ('delivery_days', models.PositiveSmallIntegerField(default=5)),
                ('category', models.CharField(choices=[('Casual Wear', 'Casual Wear'), ('Festive', 'Festive'), ('Embroidered', 'Embroidered'), ('Block Print', 'Block Print'), ('Silk & Satin', 'Silk & Satin'), ('Designer', 'Designer')], max_length=50)),
                ('fabric', models.CharField(max_length=100)),
                ('img_class', models.CharField(default='product-img-1', max_length=50)),
                ('tag', models.CharField(blank=True, choices=[('New', 'New'), ('Hot', 'Hot'), ('Sale', 'Sale'), ('Luxe', 'Luxe')], max_length=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sold', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('show_on_home', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('color_hex', models.CharField(default='#7b1e3a', max_length=20)),
                ('offer_from', models.DateField(blank=True, null=True)),
                ('offer_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('size', models.CharField(max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.order')),
            ],
        ),
    ]
