# Generated by Django 5.2.15 on 2026-06-23 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_userprofile_user_type_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="app.shop",
            ),
        ),
    ]
