# Generated by Django 5.2.15 on 2026-06-23 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_product_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.shop",
            ),
        ),
    ]
