# Generated by Django 5.2.15 on 2026-06-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_orderitem_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shop",
            name="logo",
            field=models.CharField(
                blank=True, help_text="URL to shop logo image", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="tagline",
            field=models.CharField(
                blank=True,
                help_text="A short catchy phrase for your shop",
                max_length=255,
            ),
        ),
    ]
