# Generated by Django 5.2.15 on 2026-06-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_product_is_featured_shop_logo_shop_tagline"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='e.g. {"RAM": "8GB", "Brand": "Sony"}',
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Womens Wear", "Womens Wear"),
                    ("Mens Wear", "Mens Wear"),
                    ("Electronics", "Electronics"),
                    ("Home & Living", "Home & Living"),
                    ("Others", "Others"),
                ],
                default="Others",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="fabric",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
