# Generated by Django 5.2.15 on 2026-06-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_product_specifications_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="banner",
            field=models.CharField(
                blank=True, help_text="URL to top header banner image", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="custom_categories",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='e.g. ["Electronics", "Summer Collection"]',
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(default="Others", max_length=100),
        ),
    ]
