# Generated by Django 5.2.15 on 2026-06-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_shop_banner_shop_custom_categories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="bg_color",
            field=models.CharField(
                default="#ffffff",
                help_text="Background color of the shop page",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="footer_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="footer_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="shop",
            name="footer_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
