# Generated by Django 5.2.15 on 2026-06-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_shop_bg_color_shop_footer_address_shop_footer_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="categories_heading",
            field=models.CharField(default="What we offer", max_length=255),
        ),
        migrations.AddField(
            model_name="shop",
            name="hero_heading",
            field=models.CharField(default="Taste the Finest", max_length=255),
        ),
    ]
