# Generated by Django 5.2.15 on 2026-06-23 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_shop_categories_heading_shop_hero_heading"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="app.shop",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="categories_heading",
            field=models.CharField(default="Discover Our Collection", max_length=255),
        ),
        migrations.AlterField(
            model_name="shop",
            name="hero_heading",
            field=models.CharField(default="Quality You Can Trust", max_length=255),
        ),
    ]
